# External gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate

permalink: /:title/
include: ["_pages"]
exclude:
  - "/vendor/"

# Site settings
title: Random Ren
subtitle: "Whatever I Want On The Internet"
email: wouldntyouliketoknow@idontwanttogetspammed.fu
name: Eli Ren
description: >
  Whatever I want on the internet.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/centrarium" # the subpath of your site, e.g. /blog/
url: "http://randomren.com" # the base hostname & protocol for your site
cover: "/images/header_image.jpg"
# logo: "/images/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true
highlightjs_theme: "monokai-sublime"

# Make jekyll recognise images in "images" folder as images
defaults:
  - scope:
      path: "images/throwing-water"
    values:
      image: true


# Disqus comments
disqus_shortname: randomren-com

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: RandomRen
    url: https://twitter.com/randomren1
    desc: Follow me on Twitter
    share: false

  - name: Facebook
    icon: facebook
    username: 
    url:
    desc: Friend me on Facebook
    share: false

  - name: GitHub
    icon: github
    username: randomren
    url: https://github.com/randomren
    desc: Fork me on GitHub
    share: true

  - name: LinkedIn
    icon: linkedin
    username: 
    url: 
    desc: Connect with me on LinkedIn
    share: false

  - name: Google+
    icon: google-plus
    username:
    url:
    desc: Add me to your Circles
    share: false

  - name: YouTube
    icon: youtube
    username: randomren
    url: https://www.youtube.com/channel/UCWEVSiysvAPCnA6m53IH04A?view_as=subscriber
    desc: Subscribe on YouTube
    share: true

  - name: Instagram
    icon: instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username:
    url:
    desc: Follow me on Pinterest
    share: false

  - name: SoundCloud
    icon: soundcloud
    username:
    url:
    desc: Follow me on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username:
    url:
    desc: Follow me on Tumblr
    share: false

  - name: Steam
    icon: steam
    username:
    url:
    desc: Friend me on Steam
    share: false

  - name: Dribbble
    icon: dribbble
    username:
    url:
    desc: Follow me on Dribble
    share: false

  - name: Vimeo
    icon: vimeo-square
    username:
    url:
    desc: Follow me on Vimeo
    share: false

  - name: Vine
    icon: vine
    username:
    url:
    desc: Follow me on Vine
    share: false

  - name: Reddit
    icon: reddit
    username:
    url:
    desc: Share to Reddit
    share: false

  - name: "Hacker News"
    icon: hacker-news
    username:
    url:
    desc: Share to Hacker News
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/images/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/images/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
